### ISSUE TITLE
[Feature request] Add bulk download of dataset metadata

### ISSUE THREAD

**Issue by flaneuse** [NIAID-Data-Ecosystem/nde-portal#41]
* Presumably from the search results and/or the summary pages, allow metadata download of a group of results.
* From each dataset page, enable download of that metadata.
* Not sure if it'd be actually used by anyone, but it might be cool to be able to copy the API link to get all of a search results page and/or a snippet of Python/R/curl code to fetch all the results for a query.  BUT-- not sure there's an actual (not hypothetical) use case for it.  I imagine many people would be more comfortable in Excel/csv.

See @rshabman's suggestion for the [DDE](https://github.com/biothings/discovery-app/issues/156#issue-1267537782), which outlines his use case

**Comment by rshabman** [comment]
Hello,

Following up on this download idea and API of all data.  I think the BV-BRC would be interested in this functionality if it's added.  Copying Wiriya the COR on that contract.

Reed

From: Laura Hughes ***@***.***>
Sent: Friday, June 10, 2022 11:23 AM
To: NIAID-Data-Ecosystem/nde-portal ***@***.***>
Cc: Shabman, Reed (NIH/NIAID) [E] ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] [NIAID-Data-Ecosystem/nde-portal] [Feature request] Add bulk download of dataset metadata (Issue #41)


  *   Presumably from the search results and/or the summary pages, allow metadata download of a group of results.
  *   From each dataset page, enable download of that metadata.
  *   Not sure if it'd be actually used by anyone, but it might be cool to be able to copy the API link to get all of a search results page and/or a snippet of Python/R/curl code to fetch all the results for a query. BUT-- not sure there's an actual (not hypothetical) use case for it. I imagine many people would be more comfortable in Excel/csv.

See @rshabman<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frshabman&data=05%7C01%7Creed.shabman%40nih.gov%7C655d69400e504b42689608da4af52131%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637904713924944009%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vu16jl8cUMTmuqdStFksuydR%2BBQ00TzuYM88Y0T0vd0%3D&reserved=0>'s suggestion for the DDE<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbiothings%2Fdiscovery-app%2Fissues%2F156%23issue-1267537782&data=05%7C01%7Creed.shabman%40nih.gov%7C655d69400e504b42689608da4af52131%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637904713924944009%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=dnrNv8TVcJmVPysd9GPAgC35XxNxf2W3qXoOmWV%2F%2F04%3D&reserved=0>, which outlines his use case

-
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNIAID-Data-Ecosystem%2Fnde-portal%2Fissues%2F41&data=05%7C01%7Creed.shabman%40nih.gov%7C655d69400e504b42689608da4af52131%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637904713924944009%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=hJQNGXjE9vsgOf%2Fb6JheqQ0aLLkiql2h0NZDCapSKFs%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FANOLSYWZUH4RU5JGDYJP5JDVONMV3ANCNFSM5YOBBU6A&data=05%7C01%7Creed.shabman%40nih.gov%7C655d69400e504b42689608da4af52131%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637904713924944009%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=KZ8SzyEKpcyFSL%2BlGff2Oo8xar0fF%2B6VO1tskhTiiL0%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and are confident the content is safe.

**Comment by flaneuse** [comment]
The API will be fully open and accessible for anyone to use.  Downloadable .csv files isn't implemented yet but should be straightforward to add.  Happy to connect with Wiriya and the rest of the NIAID Data Ecosystem team if you want to discuss.
