### ISSUE TITLE
Expose metrics of use/re-use

### ISSUE THREAD

**Issue by flaneuse** [NIAID-Data-Ecosystem/nde-portal#68]
To promote greater transparency into the quality / legitimacy of the dataset. Expose metrics collected by the original repo and/or internal Google Analytics.

**Comment by gtsueng** [comment]
We use `@type`: `AggregateRating` for altmetric values in outbreak.info since altmetrics provides some sort of calculated score based on all the download, citation stats. The `AggregateRating` `@type` has properties like `reviewAspect`, `ratingCount`, `ratingValue` which can be useful for different types of evaluations. Otherwise, you can use `interactionStatistic` to link it to an `InteractionCounter` object which includes properties like [interactionType](https://schema.org/interactionType) and [userInteractionCount](https://schema.org/userInteractionCount) which are quite suitable for simple download counts, page views, etc.

**Comment by candicecz** [comment]
[Example](https://data-staging.niaid.nih.gov/portal/resources/?id=Bioconductor_CluMSID)
